name: release

on:
  push:
    # Run only against semver version tags.
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:

  # Upload archives as GitHub Releases or Homebrew.
  contents: write

  # Push Docker images to Github.
  # packages: write

  # Milestone closing capability.
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    # The Github Actions environment (with variables and secrets) to use.
    environment: release
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update pkg.go.dev records
        if: github.ref_type == 'tag'
        run: go list -m "github.com/divergentcodes/jwt-block@${{ github.ref_name }}"
        env:
          GOPROXY: proxy.golang.org

      - name: Push Docker image
        run: make docker-push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_API_KEY: ${{ secrets.DOCKER_API_KEY }}

